### ISSUE TITLE
Implement the sub-settings/tool bars

### ISSUE THREAD

**Issue by kenny-67** [zurichat/zc_plugin_whiteboard#241]
![image](https://user-images.githubusercontent.com/41513164/131437040-460e4e8e-2521-4b57-baf4-bcf59deb7344.png)
![image](https://user-images.githubusercontent.com/41513164/131437077-ee0c3bc6-e849-4987-b673-19bac2a8e801.png)
![image](https://user-images.githubusercontent.com/41513164/131437285-d142300d-96fb-459c-ba22-7eaee18e03c1.png)

**Note, these are three different components and should be in different files**

**Comment by chie7tain** [comment]
can i work on this issue @kenny-67
